name: Remote Dispatch Action Initiator
#test
on: [push]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: update
          repository: PenguinMod/PenguinMod-Gui
